/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    '01.generate-quiz': ApiRouteHandler<Record<string, unknown>, unknown, never>
    '03.upload-pdf': ApiRouteHandler<Record<string, unknown>, unknown, never>
    '05.submit-answer': ApiRouteHandler<Record<string, unknown>, unknown, never>
    '07.analyze-perf': EventHandler<never, { topic: 'performance.analyzed'; data: never } | { topic: 'roadmap.generated'; data: never }>
    '08.notify-users': EventHandler<never, { topic: 'notification.sent'; data: never }>
    '10.spaced-repetition': CronHandler<{ topic: 'review.scheduled'; data: never }>
    '11.weekly-report': CronHandler<{ topic: 'report.generated'; data: never }>
    '12.cleanup-data': CronHandler<never>
    '13.chat-session': ApiRouteHandler<Record<string, unknown>, unknown, never>
    '09.daily-summary': CronHandler<{ topic: 'summary.generated'; data: never }>
    '14.system-events': EventHandler<never, never>
  }
    
}