/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    '13.get-roadmap': ApiRouteHandler<Record<string, unknown>, unknown, never>
    '11.system-events': EventHandler<never, never>
    '10.chat-session': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'rag.retrieval.requested'; data: never }>
    '09.cleanup-data': CronHandler<never>
    '08.daily-summary': CronHandler<{ topic: 'summary.generated'; data: never }>
    '07.analyze-perf': EventHandler<never, { topic: 'performance.analyzed'; data: never }>
    '05.submit-answer': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'answer.submitted'; data: never } | { topic: 'rag.retrieval.requested'; data: never }>
    '03b.upload-status': ApiRouteHandler<Record<string, unknown>, unknown, never>
    '03.upload-pdf': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'pdf.uploaded'; data: never }>
    '01.generate-quiz': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'quiz.requested'; data: never } | { topic: 'rag.retrieval.requested'; data: never }>
    '12.rag-retrieval': EventHandler<never, { topic: 'rag.retrieval.completed'; data: never }>
    '06.eval-answer': EventHandler<never, { topic: 'answer.evaluated'; data: never } | { topic: 'test.completed'; data: never }>
    '04.process-pdf': EventHandler<never, { topic: 'pdf.processed'; data: never } | { topic: 'pdf.chunk.processed'; data: never }>
    '02.gen-quiz-ai': EventHandler<never, { topic: 'quiz.generated'; data: never } | { topic: 'test.completed'; data: never }>
  }
    
}