import { StepConfig } from 'motia';

export const config: StepConfig = {
    name: '16.get-roadmap',
    type: 'api',
    path: '/get-roadmap',
    method: 'POST',
    emits: [],
    flows: ['learnlive-flow']
};

export const handler = async (ctx: any) => {
    ctx.logger.info('[16.get-roadmap] Fetching roadmap for student:', ctx.body.studentId);
    const { studentId } = ctx.body;

    // 1. Get student's performance stats from state
    const stats = await ctx.getState(`stats:${studentId}`) || {
        tests: 0,
        avgScore: 0,
        quizzesTaken: 0,
        oralTestsTaken: 0
    };

    // 2. Get student's roadmap from state (generated by Step 07)
    const roadmap = await ctx.getState(`roadmap:${studentId}`) || {
        recommendation: 'Take more tests to generate personalized roadmap',
        weakTopics: [],
        strongTopics: [],
        suggestedActions: []
    };

    // 3. Get recent test history
    const recentTests = await ctx.getState(`tests:${studentId}`) || [];

    // 4. Calculate performance trend
    const trend = stats.avgScore >= 70 ? 'improving' : 'needs-focus';
    const status = stats.tests < 3
        ? 'insufficient-data'
        : stats.avgScore >= 80
            ? 'excellent'
            : stats.avgScore >= 60
                ? 'good'
                : 'needs-improvement';

    return {
        success: true,
        studentId,
        analytics: {
            totalTests: stats.tests,
            quizzesTaken: stats.quizzesTaken || 0,
            oralTestsTaken: stats.oralTestsTaken || 0,
            averageScore: Math.round(stats.avgScore || 0),
            trend,
            status
        },
        roadmap: {
            recommendation: roadmap.recommendation,
            weakTopics: roadmap.weakTopics || [],
            strongTopics: roadmap.strongTopics || [],
            suggestedActions: roadmap.suggestedActions || [
                'Complete more quizzes to identify weak areas',
                'Practice oral tests to improve confidence',
                'Review uploaded PDF materials'
            ]
        },
        recentActivity: recentTests.slice(-5).map((test: any) => ({
            type: test.testType,
            topic: test.topic || test.question?.substring(0, 50),
            score: test.score,
            date: test.timestamp
        }))
    };
};
